CREATE TABLE MOVIES(Movie_name varchar(30),Actor varchar(40),Actress varchar(40),YOR int(4), Director varchar(40));

INSERT INTO MOVIES VALUES('K.G.F:CHAPTER 1','YASH','SRINIDHI',2018,'PRASHANTH NEEL');
INSERT INTO MOVIES VALUES('URI:THE SURGICAL STRIKE','VICKY KAUSHAL','YAMI GAUTHAM',2019,'ADITYA DHAR');
INSERT INTO MOVIES VALUES('3 IDIOTS','AAMIR KHAN','KAREENA KAPOOR',2009,'RAJKUMAR HIRANI');
INSERT INTO MOVIES VALUES('CHHICHHORE','SUSHANTH SINGH RAJPUT','SHRADDHA KAPOOR',2019,'NITESH TIWARI');
INSERT INTO MOVIES VALUES('IRON MAN','ROBERT DOWNEY JR.','GWYNETH PALTROW',2008,'JON FAVREAU');
INSERT INTO MOVIES VALUES('PK','AAMIR KHAN','ANUSKHA SHARMA',2014,'RAJKUMAR HIRANI');
SELECT * FROM MOVIES;
SELECT Movie_name,YOR from MOVIES WHERE Director='RAJKUMAR HIRANI' AND Actor='AAMIR KHAN';
SELECT Actress,YOR from MOVIES WHERE Director='RAJKUMAR HIRANI';
SELECT Movie_name,YOR from MOVIES WHERE YOR BETWEEN 2009 AND 2019 ORDER BY YOR;
SELECT Actor,Actress FROM MOVIES WHERE YOR BETWEEN 2010 AND 2018 ORDER BY Actor;
SELECT Movie_name FROM MOVIES ORDER BY YOR DESC;
SELECT Movie_name,Actor,Actress FROM MOVIES WHERE Director!='RAJKUMAR HIRANI' ORDER BY YOR;